name: CI

on:
  pull_request: {}
  push: { branches: [master] }

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        lfs: true
    - uses: ./.github/actions/buildProject
      with:
        cypher: ${{ secrets.UNITY_LICENSE }}
        platform: Android
        buildName: ${{ secrets.PROJECT_NAME }}
    - uses: actions/upload-artifact@v1
        with:
          name: Build
          path: build
    # - run: cp -rf ./Builds/WebGL/${{secrets.PROJECT_NAME}}/ ${{secrets.PROJECT_NAME}}
    # - name: Deploy
    #   uses: JamesIves/github-pages-deploy-action@releases/v2
    #   env:
    #     ACCESS_TOKEN: ${{ secrets.GITHUB_PAT }}
    #     BRANCH: gh-pages
    #     FOLDER: ${{ secrets.PROJECT_NAME }}
    #     BASE_BRANCH: master
