name: Actions 😎

on:
 pull_request: {}
 push: { branches: [master] }

env:
 UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

jobs:
 buildAndTestForSomePlatforms:
   name: Tests on version ${{ matrix.unityVersion }}
   runs-on: ubuntu-latest
   strategy:
     fail-fast: false
     matrix:
       unityVersion:
         - 2019.4.13f1
   steps:
     - uses: actions/checkout@v2
       with:
         lfs: true
     - uses: actions/cache@v1.1.0
       with:
         path: Library
         key: Library
     - uses: webbertakken/unity-test-runner@v1.4
       id: testRunner
       with:
         testMode: editmode
         unityVersion: ${{ matrix.unityVersion }}
         customParameters: -enableCodeCoverage
     - uses: actions/upload-artifact@v1
       with:
         name: Test results (all modes)
         path: ${{ steps.testRunner.outputs.artifactsPath }}
     - name: code coverage
       run: xvfb-run --auto-servernum --server-args='-screen 0 640x480x24' /opt/Unity/Editor/Unity -projectPath "$GITHUB_WORKSPACE/" -batchmode -enableCodeCoverage -coverageResultsPath ./editmode-coverage -coverageOptions generateHtmlReport;generateBadgeReport -quit
     - name: Deploy 🚀
       uses: JamesIves/github-pages-deploy-action@3.7.1
       with:
         GITHUB_TOKEN: ${{ secrets.TOKEN }}
         BRANCH: gh-pages
         FOLDER: ./editmode-coverage
         CLEAN: true
